# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap
from PyQt5.QtWidgets import QFileDialog
from imgInfo import imgInfo

class Ui_Dialog(object):

    new = imgInfo()

    def atualiza(self):
        pass

    def function_bTop(self):
        fileName = QFileDialog.getOpenFileName() 
        self.new.set_urlTopo(str(fileName[0]))

    def function_bBack(self):
        fileName = QFileDialog.getOpenFileName() 
        self.new.set_urlBackground(fileName)
    
    def function_bProd(self):
        fileName = QFileDialog.getOpenFileNames() 
        self.new.set_urlProdutos(fileName[0])

    def function_maxProd(self):
        self.new.set_maxPro(self.maxProd.value())

    def function_coluna(self):
        self.new.set_coluna(self.colunas.value())

    def function_Preview(self):
        self.new.set_fileName("preview")
        self.new.createImage()
        self.label_5.setPixmap(QtGui.QPixmap("preview.png").scaledToWidth(300))

        
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(652, 451)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setMinimumSize(QtCore.QSize(0, 0))
        self.frame.setStyleSheet("background-color: rgb(206, 206, 206);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setMinimumSize(QtCore.QSize(333, 416))
        self.label_5.setMaximumSize(QtCore.QSize(333, 416))
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.horizontalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(Dialog)
        self.frame_2.setMinimumSize(QtCore.QSize(130, 0))
        self.frame_2.setMaximumSize(QtCore.QSize(20, 16777215))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setContentsMargins(8, 0, 0, 0)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.bTop = QtWidgets.QPushButton(self.frame_2)
        self.bTop.setObjectName("bTop")
        self.verticalLayout.addWidget(self.bTop)
        self.bBack = QtWidgets.QPushButton(self.frame_2)
        self.bBack.setObjectName("bBack")
        self.verticalLayout.addWidget(self.bBack)
        self.bProd = QtWidgets.QPushButton(self.frame_2)
        self.bProd.setObjectName("bProd")
        self.verticalLayout.addWidget(self.bProd)
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.maxProd = QtWidgets.QSpinBox(self.frame_2)
        self.maxProd.setMinimumSize(QtCore.QSize(0, 0))
        self.maxProd.setMaximumSize(QtCore.QSize(40, 16777215))
        self.maxProd.setAlignment(QtCore.Qt.AlignCenter)
        self.maxProd.setObjectName("maxProd")
        self.verticalLayout.addWidget(self.maxProd)
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.colunas = QtWidgets.QSpinBox(self.frame_2)
        self.colunas.setMaximumSize(QtCore.QSize(40, 16777215))
        self.colunas.setAlignment(QtCore.Qt.AlignCenter)
        self.colunas.setObjectName("colunas")
        self.verticalLayout.addWidget(self.colunas)
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.validade = QtWidgets.QDateEdit(self.frame_2)
        self.validade.setMaximumSize(QtCore.QSize(80, 16777215))
        self.validade.setDateTime(QtCore.QDateTime(QtCore.QDate(2021, 4, 1), QtCore.QTime(0, 0, 0)))
        self.validade.setObjectName("validade")
        self.verticalLayout.addWidget(self.validade)
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.saveName = QtWidgets.QLineEdit(self.frame_2)
        self.saveName.setObjectName("saveName")
        self.verticalLayout.addWidget(self.saveName)
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout.addWidget(self.frame_2)

        
        self.bTop.clicked.connect(self.function_bTop)

        self.bBack.clicked.connect(self.function_bBack)

        self.bProd.clicked.connect(self.function_bProd)

        #produtos pro ultimo
            
        self.maxProd.valueChanged.connect(self.function_maxProd)
        self.maxProd.setValue(self.new.get_maxProducts())
       
        self.colunas.valueChanged.connect(self.function_coluna)
        self.colunas.setValue(self.new.get_coluna())

        self.pushButton.clicked.connect(self.function_Preview)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.bTop.setText(_translate("Dialog", "Topo"))
        self.bBack.setText(_translate("Dialog", "Background"))
        self.bProd.setText(_translate("Dialog", "Produtos"))
        self.label_2.setText(_translate("Dialog", "Número de Produtos:"))
        self.label_3.setText(_translate("Dialog", "Número de Colunas:"))
        self.label.setText(_translate("Dialog", "Validade:"))
        self.validade.setDisplayFormat(_translate("Dialog", "dd/MM/yyyy"))
        self.label_4.setText(_translate("Dialog", "Salvar como:"))
        self.saveName.setText(_translate("Dialog", "Arquivo"))
        self.pushButton.setText(_translate("Dialog", "Salvar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
